### ISSUE TITLE
TODO / BUGS

### ISSUE THREAD

**Issue by pandaa-be** [PandaOaseBE/MobsLite#3]
TODO

- [ ] Natural Biome Spawning
- [ ] Natural Structure Spawning
- [ ] Better Movement
- [ ] Smoother Knockback
- [ ] Edit XP Drops for some Mobs
- [ ] Add chances for Lootdrops for some Mobs
